// File: data-sleman.js
// Database Kelurahan & Kepanewonan SMPN Sleman

///////////////////////

const SMPN_DOMISILI = {
  "SMP Negeri 1 Berbah": [
    "Berbah, Jogotirto",
    "Berbah, Kalitirto",
    "Berbah, Sendangtirto",
    "Berbah, Tegaltirto",
    "Kalasan, Purwomartani",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Prambanan, Madurejo",
    "Depok, Maguwoharjo"
  ],
  "SMP Negeri 2 Berbah": [
    "Berbah, Jogotirto",
    "Berbah, Kalitirto",
    "Berbah, Sendangtirto",
    "Berbah, Tegaltirto",
    "Depok, Maguwoharjo",
    "Kalasan, Purwomartani",
    "Prambanan, Madurejo",
    "Prambanan, Sumberharjo"
  ],
  "SMP Negeri 3 Berbah": [
    "Berbah, Jogotirto",
    "Berbah, Kalitirto",
    "Berbah, Sendangtirto",
    "Berbah, Tegaltirto",
    "Prambanan, Madurejo",
    "Prambanan, Sumberharjo"
  ],
  "SMP Negeri 1 Cangkringan": [
    "Cangkringan, Argomulyo",
    "Cangkringan, Glagaharjo",
    "Cangkringan, Kepuharjo",
    "Cangkringan, Umbulharjo",
    "Cangkringan, Wukirsari",
    "Ngemplak, Bimomartani",
    "Ngemplak, Sindumartani",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Widodomartani",
    "Pakem, Pakembinangun"
  ],
  "SMP Negeri 2 Cangkringan": [
    "Cangkringan, Argomulyo",
    "Cangkringan, Glagaharjo",
    "Cangkringan, Kepuharjo",
    "Cangkringan, Umbulharjo",
    "Cangkringan, Wukirsari",
    "Pakem, Hargobinangun",
    "Pakem, Pakembinangun",
    "Ngemplak, Bimomartani",
    "Ngemplak, Sindumartani"
  ],
  "SMP Negeri 1 Depok": [
    "Depok, Caturtunggal",
    "Depok, Condongcatur",
    "Depok, Maguwoharjo",
    "Mlati, Sinduadi",
    "Ngaglik, Minomartani",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Ngemplak, Wedomartani"
  ],
  "SMP Negeri 2 Depok": [
    "Berbah, Kalitirto",
    "Depok, Caturtunggal",
    "Depok, Condongcatur",
    "Depok, Maguwoharjo",
    "Kalasan, Purwomartani",
    "Ngaglik, Minomartani",
    "Ngaglik, Sinduharjo",
    "Ngemplak, Wedomartani"
  ],
  "SMP Negeri 3 Depok": [
    "Berbah, Kalitirto",
    "Berbah, Sendangtirto",
    "Berbah, Tegaltirto",
    "Depok, Caturtunggal",
    "Depok, Condongcatur",
    "Depok, Maguwoharjo",
    "Kalasan, Purwomartani",
    "Ngaglik, Minomartani",
    "Ngemplak, Wedomartani"
  ],
  "SMP Negeri 4 Depok": [
    "Berbah, Kalitirto",
    "Berbah, Tegaltirto",
    "Depok, Caturtunggal",
    "Depok, Condongcatur",
    "Depok, Maguwoharjo",
    "Kalasan, Purwomartani",
    "Ngaglik, Minomartani",
    "Ngemplak, Wedomartani"
  ],
  "SMP Negeri 5 Depok": [
    "Depok, Caturtunggal",
    "Depok, Condongcatur",
    "Depok, Maguwoharjo",
    "Mlati, Sinduadi",
    "Ngaglik, Minomartani",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Ngaglik, Sukoharjo"
  ],
  "SMP Negeri 1 Gamping": [
    "Gamping, Ambarketawang",
    "Gamping, Balecatur",
    "Gamping, Banyuraden",
    "Gamping, Nogotirto",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidomulyo"
  ],
  "SMP Negeri 2 Gamping": [
    "Gamping, Ambarketawang",
    "Gamping, Banyuraden",
    "Gamping, Nogotirto",
    "Gamping, Trihanggo",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidomoyo",
    "Mlati, Sendangadi",
    "Mlati, Sinduadi",
    "Mlati, Tirtoadi",
    "Mlati, Tlogoadi"
  ],
  "SMP Negeri 3 Gamping": [
    "Gamping, Ambarketawang",
    "Gamping, Balecatur",
    "Gamping, Banyuraden",
    "Gamping, Nogotirto",
    "Gamping, Trihanggo",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidomoyo",
    "Mlati, Tirtoadi",
    "Mlati, Tlogoadi"
  ],
  "SMP Negeri 4 Gamping": [
    "Gamping, Ambarketawang",
    "Gamping, Balecatur",
    "Gamping, Banyuraden",
    "Gamping, Nogotirto",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidomulyo"
  ],
  "SMP Negeri 1 Godean": [
    "Gamping, Balecatur",
    "Godean, Sidoagung",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidoluhur",
    "Godean, Sidomoyo",
    "Godean, Sidomulyo",
    "Godean, Sidorejo",
    "Minggir, Sendangagung",
    "Minggir, Sendangarum",
    "Minggir, Sendangmulyo",
    "Minggir, Sendangrejo",
    "Minggir, Sendangsari",
    "Moyudan, Sumberagung",
    "Moyudan, Sumberarum",
    "Moyudan, Sumberrahayu",
    "Moyudan, Sumbersari",
    "Seyegan, Margodadi",
    "Seyegan, Margoluwih",
    "Seyegan, Margokaton"
  ],
  "SMP Negeri 2 Godean": [
    "Gamping, Ambarketawang",
    "Gamping, Nogotirto",
    "Godean, Sidoagung",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidoluhur",
    "Godean, Sidomoyo",
    "Godean, Sidomulyo",
    "Godean, Sidorejo",
    "Mlati, Tirtoadi",
    "Moyudan, Sumberarum",
    "Seyegan, Margodadi",
    "Seyegan, Margoluwih",
    "Gamping, Banyuraden"
  ],
  "SMP Negeri 3 Godean": [
    "Gamping, Ambarketawang",
    "Gamping, Balecatur",
    "Gamping, Banyuraden",
    "Gamping, Nogotirto",
    "Godean, Sidoagung",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidoluhur",
    "Godean, Sidomoyo",
    "Godean, Sidomulyo",
    "Godean, Sidorejo",
    "Moyudan, Sumberagung",
    "Moyudan, Sumbersari",
    "Seyegan, Margoluwih"
  ],
  "SMP Negeri 1 Kalasan": [
    "Berbah, Kalitirto",
    "Berbah, Tegaltirto",
    "Depok, Maguwoharjo",
    "Kalasan, Purwomartani",
    "Kalasan, Selomartani",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Prambanan, Bokoharjo",
    "Prambanan, Madurejo",
    "Prambanan, Sumberharjo"
  ],
  "SMP Negeri 2 Kalasan": [
    "Berbah, Kalitirto",
    "Kalasan, Purwomartani",
    "Kalasan, Selomartani",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Ngemplak, Bimomartani",
    "Ngemplak, Wedomartani",
    "Ngemplak, Widodomartani"
  ],
  "SMP Negeri 3 Kalasan": [
    "Berbah, Kalitirto",
    "Depok, Condongcatur",
    "Depok, Maguwoharjo",
    "Kalasan, Purwomartani",
    "Kalasan, Selomartani",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Ngemplak, Wedomartani"
  ],
  "SMP Negeri 4 Kalasan": [
    "Berbah, Kalitirto",
    "Kalasan, Purwomartani",
    "Kalasan, Selomartani",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Ngemplak, Bimomartani",
    "Ngemplak, Sindumartani",
    "Prambanan, Bokoharjo",
    "Prambanan, Madurejo"
  ],
  "SMP Negeri 1 Minggir": [
    "Godean, Sidorejo",
    "Minggir, Sendangagung",
    "Minggir, Sendangarum",
    "Minggir, Sendangmulyo",
    "Minggir, Sendangrejo",
    "Minggir, Sendangsari",
    "Moyudan, Sumberagung",
    "Moyudan, Sumberarum",
    "Moyudan, Sumberrahayu",
    "Seyegan, Margokaton",
    "Tempel, Banyurejo"
  ],
  "SMP Negeri 1 Mlati": [
    "Gamping, Trihanggo",
    "Godean, Sidomoyo",
    "Mlati, Sendangadi",
    "Mlati, Sinduadi",
    "Mlati, Sumberadi",
    "Mlati, Tirtoadi",
    "Mlati, Tlogoadi",
    "Seyegan, Margodadi",
    "Seyegan, Margokaton",
    "Seyegan, Margoluwih",
    "Seyegan, Margomulyo",
    "Sleman, Tridadi"
  ],
  "SMP Negeri 2 Mlati": [
    "Depok, Caturtunggal",
    "Gamping, Trihanggo",
    "Mlati, Sendangadi",
    "Mlati, Sinduadi",
    "Mlati, Sumberadi",
    "Mlati, Tirtoadi",
    "Mlati, Tlogoadi",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Sleman, Tridadi"
  ],
  "SMP Negeri 3 Mlati": [
    "Gamping, Nogotirto",
    "Gamping, Trihanggo",
    "Godean, Sidomoyo",
    "Mlati, Sendangadi",
    "Mlati, Sinduadi",
    "Mlati, Sumberadi",
    "Mlati, Tirtoadi",
    "Mlati, Tlogoadi",
    "Seyegan, Margomulyo",
    "Sleman, Tridadi"
  ],
  "SMP Negeri 1 Moyudan": [
    "Godean, Sidoagung",
    "Godean, Sidoarum",
    "Godean, Sidokarto",
    "Godean, Sidoluhur",
    "Godean, Sidomulyo",
    "Godean, Sidorejo",
    "Minggir, Sendangagung",
    "Minggir, Sendangarum",
    "Minggir, Sendangmulyo",
    "Moyudan, Sumberagung",
    "Moyudan, Sumberarum",
    "Moyudan, Sumberrahayu",
    "Moyudan, Sumbersari"
  ],
  "SMP Negeri 2 Moyudan": [
    "Godean, Sidorejo",
    "Godean, Sidoluhur",
    "Minggir, Sendangagung",
    "Minggir, Sendangarum",
    "Minggir, Sendangmulyo",
    "Minggir, Sendangrejo",
    "Moyudan, Sumberagung",
    "Moyudan, Sumberarum",
    "Moyudan, Sumberrahayu",
    "Moyudan, Sumbersari"
  ],
  "SMP Negeri 1 Ngaglik": [
    "Mlati, Sendangadi",
    "Ngaglik, Donoharjo",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Ngaglik, Sukoharjo",
    "Pakem, Purwobinangun",
    "Pakem, Candibinangun",
    "Sleman, Pandowoharjo",
    "Sleman, Tridadi",
    "Sleman, Trimulyo",
    "Turi, Donokerto"
  ],
  "SMP Negeri 2 Ngaglik": [
    "Ngaglik, Donoharjo",
    "Ngaglik, Minomartani",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Ngaglik, Sukoharjo",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Wedomartani",
    "Pakem, Candibinangun",
    "Pakem, Harjobinangun",
    "Depok, Condongcatur"
  ],
  "SMP Negeri 3 Ngaglik": [
    "Ngaglik, Donoharjo",
    "Ngaglik, Minomartani",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Ngaglik, Sukoharjo",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Wedomartani",
    "Pakem, Harjobinangun",
    "Pakem, Pakembinangun",
    "Pakem, Purwobinangun",
    "Sleman, Pandowoharjo",
    "Depok, Condongcatur"
  ],
  "SMP Negeri 4 Ngaglik": [
    "Depok, Condongcatur",
    "Mlati, Sendangadi",
    "Ngaglik, Donoharjo",
    "Ngaglik, Minomartani",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sariharjo",
    "Ngaglik, Sinduharjo",
    "Pakem, Candibinangun",
    "Pakem, Harjobinangun",
    "Sleman, Pandowoharjo",
    "Turi, Donokerto"
  ],
  "SMP Negeri 1 Ngemplak": [
    "Cangkringan, Argomulyo",
    "Cangkringan, Wukirsari",
    "Depok, Maguwoharjo",
    "Kalasan, Selomartani",
    "Ngaglik, Sukoharjo",
    "Ngemplak, Bimomartani",
    "Ngemplak, Sindumartani",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Wedomartani",
    "Ngemplak, Widodomartani"
  ],
  "SMP Negeri 2 Ngemplak": [
    "Cangkringan, Argomulyo",
    "Kalasan, Purwomartani",
    "Kalasan, Selomartani",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Ngaglik, Sukoharjo",
    "Ngemplak, Bimomartani",
    "Ngemplak, Sindumartani",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Wedomartani",
    "Ngemplak, Widodomartani"
  ],
  "SMP Negeri 1 Pakem": [
    "Cangkringan, Glagaharjo",
    "Cangkringan, Kepuharjo",
    "Cangkringan, Umbulharjo",
    "Cangkringan, Wukirsari",
    "Cangkringan, Argomulyo",
    "Ngaglik, Sukoharjo",
    "Ngemplak, Umbulmartani",
    "Pakem, Candibinangun",
    "Pakem, Hargobinangun",
    "Pakem, Harjobinangun",
    "Pakem, Pakembinangun",
    "Pakem, Purwobinangun",
    "Turi, Donokerto"
  ],
  "SMP Negeri 2 Pakem": [
    "Cangkringan, Glagaharjo",
    "Cangkringan, Kepuharjo",
    "Cangkringan, Umbulharjo",
    "Cangkringan, Wukirsari",
    "Cangkringan, Argomulyo",
    "Ngemplak, Umbulmartani",
    "Pakem, Candibinangun",
    "Pakem, Hargobinangun",
    "Pakem, Harjobinangun",
    "Pakem, Pakembinangun",
    "Pakem, Purwobinangun",
    "Turi, Donokerto",
    "Turi, Girikerto"
  ],
  "SMP Negeri 3 Pakem": [
    "Cangkringan, Wukirsari",
    "Ngaglik, Donoharjo",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sukoharjo",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Widodomartani",
    "Pakem, Candibinangun",
    "Pakem, Hargobinangun",
    "Pakem, Harjobinangun",
    "Pakem, Pakembinangun",
    "Pakem, Purwobinangun",
    "Turi, Donokerto"
  ],
  "SMP Negeri 4 Pakem": [
    "Cangkringan, Wukirsari",
    "Cangkringan, Umbulharjo",
    "Cangkringan, Argomulyo",
    "Ngaglik, Donoharjo",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sinduharjo",
    "Ngaglik, Sukoharjo",
    "Ngaglik, Minomartani",
    "Ngemplak, Umbulmartani",
    "Ngemplak, Wedomartani",
    "Ngemplak, Widodomartani",
    "Pakem, Candibinangun",
    "Pakem, Hargobinangun",
    "Pakem, Harjobinangun",
    "Pakem, Pakembinangun",
    "Pakem, Purwobinangun",
    "Turi, Donokerto"
  ],
  "SMP Negeri 1 Prambanan": [
    "Berbah, Jogotirto",
    "Berbah, Kalitirto",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Prambanan, Bokoharjo",
    "Prambanan, Gayamharjo",
    "Prambanan, Madurejo",
    "Prambanan, Sambirejo",
    "Prambanan, Sumberharjo",
    "Prambanan, Wukirharjo"
  ],
  "SMP Negeri 2 Prambanan": [
    "Berbah, Jogotirto",
    "Prambanan, Bokoharjo",
    "Prambanan, Gayamharjo",
    "Prambanan, Madurejo",
    "Prambanan, Sambirejo",
    "Prambanan, Sumberharjo",
    "Prambanan, Wukirharjo"
  ],
  "SMP Negeri 3 Prambanan": [
    "Berbah, Jogotirto",
    "Kalasan, Tamanmartani",
    "Prambanan, Bokoharjo",
    "Prambanan, Gayamharjo",
    "Prambanan, Madurejo",
    "Prambanan, Sambirejo",
    "Prambanan, Sumberharjo",
    "Prambanan, Wukirharjo"
  ],
  "SMP Negeri 4 Prambanan": [
    "Berbah, Jogotirto",
    "Berbah, Kalitirto",
    "Berbah, Sendangtirto",
    "Kalasan, Tamanmartani",
    "Kalasan, Tirtomartani",
    "Prambanan, Bokoharjo",
    "Prambanan, Gayamharjo",
    "Prambanan, Madurejo",
    "Prambanan, Sambirejo",
    "Prambanan, Sumberharjo",
    "Prambanan, Wukirharjo"
  ],
  "SMP Negeri 1 Seyegan": [
    "Godean, Sidoagung",
    "Godean, Sidorejo",
    "Minggir, Sendangmulyo",
    "Minggir, Sendangrejo",
    "Minggir, Sendangsari",
    "Minggir, Sendangagung",
    "Mlati, Sumberadi",
    "Mlati, Tirtoadi",
    "Seyegan, Margoagung",
    "Seyegan, Margodadi",
    "Seyegan, Margokaton",
    "Seyegan, Margoluwih",
    "Seyegan, Margomulyo",
    "Sleman, Caturharjo",
    "Tempel, Tambakrejo"
  ],
  "SMP Negeri 1 Sleman": [
    "Mlati, Sendangadi",
    "Mlati, Sumberadi",
    "Ngaglik, Sariharjo",
    "Sleman, Caturharjo",
    "Sleman, Pandowoharjo",
    "Sleman, Tridadi",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Tempel, Margorejo",
    "Tempel, Mororejo",
    "Tempel, Sumberrejo",
    "Turi, Bangunkerto",
    "Turi, Donokerto"
  ],
  "SMP Negeri 2 Sleman": [
    "Mlati, Sendangadi",
    "Mlati, Sumberadi",
    "Mlati, Tirtoadi",
    "Mlati, Tlogoadi",
    "Seyegan, Margoagung",
    "Seyegan, Margomulyo",
    "Sleman, Caturharjo",
    "Sleman, Pandowoharjo",
    "Sleman, Tridadi",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Tempel, Margorejo",
    "Tempel, Mororejo",
    "Turi, Bangunkerto",
    "Turi, Donokerto"
  ],
  "SMP Negeri 3 Sleman": [
    "Mlati, Sendangadi",
    "Mlati, Sinduadi",
    "Mlati, Sumberadi",
    "Mlati, Tlogoadi",
    "Ngaglik, Donoharjo",
    "Ngaglik, Sardonoharjo",
    "Ngaglik, Sariharjo",
    "Sleman, Caturharjo",
    "Sleman, Pandowoharjo",
    "Sleman, Tridadi",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Gamping, Trihanggo"
  ],
  "SMP Negeri 4 Sleman": [
    "Mlati, Sumberadi",
    "Ngaglik, Donoharjo",
    "Ngaglik, Sariharjo",
    "Sleman, Caturharjo",
    "Sleman, Pandowoharjo",
    "Sleman, Tridadi",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Tempel, Margorejo",
    "Turi, Bangunkerto",
    "Turi, Donokerto"
  ],
  "SMP Negeri 5 Sleman": [
    "Mlati, Sendangadi",
    "Ngaglik, Donoharjo",
    "Ngaglik, Sariharjo",
    "Sleman, Caturharjo",
    "Sleman, Pandowoharjo",
    "Sleman, Tridadi",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Turi, Donokerto"
  ],
  "SMP Negeri 1 Tempel": [
    "Seyegan, Margoagung",
    "Sleman, Caturharjo",
    "Sleman, Pandowoharjo",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Tempel, Banyurejo",
    "Tempel, Lumbungrejo",
    "Tempel, Margorejo",
    "Tempel, Merdikorejo",
    "Tempel, Mororejo",
    "Tempel, Pondokrejo",
    "Tempel, Sumberrejo",
    "Tempel, Tambakrejo",
    "Turi, Bangunkerto"
  ],
  "SMP Negeri 2 Tempel": [
    "Minggir, Sendangrejo",
    "Minggir, Sendangsari",
    "Minggir, Sendangagung",
    "Seyegan, Margoagung",
    "Seyegan, Margokaton",
    "Seyegan, Margomulyo",
    "Seyegan, Margodadi",
    "Sleman, Caturharjo",
    "Tempel, Banyurejo",
    "Tempel, Pondokrejo",
    "Tempel, Sumberrejo",
    "Tempel, Tambakrejo"
  ],
  "SMP Negeri 3 Tempel": [
    "Seyegan, Margoagung",
    "Sleman, Caturharjo",
    "Sleman, Triharjo",
    "Tempel, Banyurejo",
    "Tempel, Lumbungrejo",
    "Tempel, Margorejo",
    "Tempel, Mororejo",
    "Tempel, Pondokrejo",
    "Tempel, Sumberrejo",
    "Tempel, Tambakrejo"
  ],
  "SMP Negeri 4 Tempel": [
    "Sleman, Caturharjo",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Sleman, Lumbungrejo",
    "Tempel, Margorejo",
    "Tempel, Merdikorejo",
    "Tempel, Mororejo",
    "Tempel, Pondokrejo",
    "Turi, Bangunkerto",
    "Turi, Donokerto",
    "Turi, Wonokerto"
  ],
  "SMP Negeri 1 Turi": [
    "Ngaglik, Donoharjo",
    "Pakem, Candibinangun",
    "Pakem, Harjobinangun",
    "Pakem, Purwobinangun",
    "Sleman, Trimulyo",
    "Tempel, Margorejo",
    "Tempel, Merdikorejo",
    "Turi, Bangunkerto",
    "Turi, Donokerto",
    "Turi, Girikerto",
    "Turi, Wonokerto"
  ],
  "SMP Negeri 2 Turi": [
    "Pakem, Purwobinangun",
    "Sleman, Caturharjo",
    "Sleman, Triharjo",
    "Sleman, Trimulyo",
    "Tempel, Lumbungrejo",
    "Tempel, Margorejo",
    "Tempel, Merdikorejo",
    "Turi, Bangunkerto",
    "Turi, Donokerto",
    "Turi, Girikerto",
    "Turi, Wonokerto"
  ],
  "SMP Negeri 3 Turi": [
    "Ngaglik, Donoharjo",
    "Ngaglik, Sardonoharjo",
    "Ngemplak, Umbulmartani",
    "Pakem, Candibinangun",
    "Pakem, Hargobinangun",
    "Pakem, Harjobinangun",
    "Pakem, Pakembinangun",
    "Pakem, Purwobinangun",
    "Turi, Bangunkerto",
    "Turi, Donokerto",
    "Turi, Girikerto",
    "Turi, Wonokerto",
    "Tempel, Merdikorejo",
    "Sleman, Trimulyo"
  ]
};

/////////////////


// Function untuk build reverse map (sama seperti sebelumnya)
function buildReverseMap(data) {
  const result = {};
  for(const smpn in data) {
    data[smpn].forEach(area => {
      const normalized = area.replace(/\s+/g, ' ').trim().toLowerCase();
      if(!result[normalized]) {
        result[normalized] = [];
      }
      result[normalized].push(smpn);
    });
  }
  return result;
}

const KELURAHAN_TO_SMPN = buildReverseMap(SMPN_DOMISILI_DATA);
